spring.application.name=backend

spring.datasource.url=jdbc:mysql://localhost:3306/foodrescue_db
spring.datasource.username=root
spring.datasource.password=diya1603

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
jwt.secret=foodrescue-development-secret-key-change-later